apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  steps:
    - name: install-dependencies
      image: python:3.10
      script: |
        #!/bin/bash
        set -e
        pip install --upgrade pip
        pip install -r /workspace/my-repo/requirements.txt
        pip install nose

    - name: run-tests
      image: python:3.10
      script: |
        #!/bin/bash
        set -e
        nosetests /workspace/my-re
